config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :albums
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :rsvps
  # resources :albums
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/album.rb
class Album < ApplicationRecord
  has_many_attached :photos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/rsvp.rb
class Rsvp < ApplicationRecord
  # belongs_to :user
  validates :name, :attendance, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  # http_basic_authenticate_with name: "zoe", password: "scotland2023"
  http_basic_authenticate_with :name => "guest", :password => "scotland2023"

  def index
    @albums = Album.all
    # @album = Album.find(params[:id])
    @album = Album.first
  end

  def show
    @album = Album.find(params[:id])
    @photo_album = Album.first
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to albums_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    # @album = Album.find(params[:id])
    @album = Album.first
    @photo_album = Album.first
  end

  def update
    @album = Album.find(params[:id])
    @album.update(album_params)
    redirect_to album_path(@album)
  end

  def destroy
    @photo_album = Album.first
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to album_path(@album), status: :see_other
  end

  private

  def album_params
    params.require(:album).permit(:title, :description, photos: [])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  # before_action :configure_permitted_parameters, if: :devise_controller?

  # def configure_permitted_parameters
  #   # For additional fields in app/views/devise/registrations/new.html.erb
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

  #   # For additional in app/views/devise/registrations/edit.html.erb
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  # end
  # http_basic_authenticate_with :password => "Scotland2023"
  # http_basic_authenticate_with :name => "guest", :password => "scotland2023"


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: :home
  # def home
  # end
  # http_basic_authenticate_with name: "zoe", password: "scotland2023", except: :index

  # http_basic_authenticate_with name: "zoe", password: "scotland2023"
  # http_basic_authenticate_with :password => "Scotland2023", :username => "zoe"
  def home
    @photo_album = Album.first
    # @rsvp_link = ALbum.last
  end
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  http_basic_authenticate_with :name => "guest", :password => "scotland2023"

  def index
    @rsvps = Rsvp.all
    @total_participants = 0
    @rsvps.each do |rsvp|
      @total_participants += 1 if rsvp.attendance == "Yes"
    end
  end

  def edit
    @rsvp = Rsvp.find(:id)
  end

  def update
    @rsvp = Rsvp.find(:id)
    @vip.update(rsvp_params)
  end

  def new
    @rsvp = Rsvp.new
  end

  def destroy
    @rsvp = Rsvp.find(:id)
    @rsvp.destroy
    redirect_to root_path
  end

  def show
    @rsvps = Rsvp.all
  end

  def create
    # @wedding_guest = WeddingGuest.find(params[:wedding_guests_id])
    @rsvp = Rsvp.new(rsvp_params)
    # @rsvp.save
    # @wedding = Wedding.find(params[:wedding_id])
    # @rsvp.wedding_id = @wedding.id
    if @rsvp.save
      redirect_to root_path, notice: "Thank you for filling out our form!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def rsvp_params
    params.require(:rsvp).permit(:name, :song, :attendance, :diet)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_album.html.erb
<div id="<%= dom_id album %>">
  <p>
    <strong>Title:</strong>
    <%= album.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= album.description %>
  </p>

</div>

app/views/albums/_form.html.erb
<%= simple_form_for(@album) do |f| %>
  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<div class="album-index">
  <div class="album-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dfipoufmj/image/upload/v1666015811/DSC02450_dmkao8.jpg);">
    <div class="home-text">
      <%= link_to "Back", album_path(@photo_album), id: "edit-back-button" %>
    </div>
  </div>
</div>
<div class="add-photo-zone">
  <div class="add-photo-area">
    <h1>Add your own photos to our album!</h1>
    <div class="add-photo-container">
      <div class="add-photo-bar">
        <%= simple_form_for(@album) do |f| %>
          <div class="form-inputs">
            <%= f.input :photos, as: :file, input_html: { multiple: true } %>
            <%= f.button :submit, id: "update-album-btn" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/albums/index.html.erb
<%# <div class="album-index">
  <div class="album-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dfipoufmj/image/upload/v1666015811/DSC02450_dmkao8.jpg);">
    <div class="home-text">
      <a href="/"><h2>HOME</h2></a>
    </div>
  </div>
</div>
<div id="albums" >
  <div class="album-card-text" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dfipoufmj/image/upload/v1666015814/DSC02519_gufztr.jpg); background-size: 500px; background-position: center;">
    <div class="album-card-text-content">
      <h1>SHARED PHOTO ALBUM</h1>
      <p>All these photographs will be hand selected to go into our scrap book for after the wedding, so whether they'll make us howl with laughter, shed a few tears or smile fondly, add as many as you can and we can all reminisce!</p>
      <h2>Feel free to upload your own pictures!</h2>
    </div>
  </div>
</div>
<div class="footer">
  <a id="schedule">
    <p>Built by the boss man bro RORY JACKSON</p>
  </a>
</div> %>
<p>index</p>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render "form", album: @album %>


<div>
  <%= link_to "Back to albums", albums_path %>
</div>

app/views/albums/show.html.erb
<div class="album-index">
  <div class="album-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dfipoufmj/image/upload/v1666015811/DSC02450_dmkao8.jpg);">
    <div class="home-text">
      <a href="/"><h2>HOME</h2></a>
    </div>
  </div>
</div>
<div class="edit">
  <%= link_to "Add Photos", edit_album_path(@photo_album), id: "add-photo-button" %>
  <%# <a href="/albums/1/edit"><h2 id="">Add Photos</h2></a> %>
</div>
<p style="padding: 20px">All these photographs will be hand selected to go into our scrap book for after the wedding, so whether they'll make us howl with laughter, shed a few tears or smile fondly, add as many as you can and we can all reminisce!</p>
<div class="album-list">
  <% @album.photos.each do |photo| %>
    <div class="album-list-box">
      <%= cl_image_tag photo.key, class: "album-list-photo" %>
    </div>
    <%# <div class="delete image">
      <%= link_to "Remove", albums_path(photo), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    <%# </div> %>
  <% end %>
</div>
<div class="footer">
  <a id="schedule">
    <p>Built by the boss man bro RORY JACKSON</p>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zoeandcameronapp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%# <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
        <%= javascript_include_tag "/assets/application.js", "data-turbo-track": "reload", defer: true %>

    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="http://fonts.cdnfonts.com/css/allegedly" rel="stylesheet">
    <style>
      @import url('http://fonts.cdnfonts.com/css/allegedly');
    </style>
    <link href="http://fonts.cdnfonts.com/css/balechin-royalo" rel="stylesheet">
    <style>
      @import url('http://fonts.cdnfonts.com/css/balechin-royalo');
    </style>
  </head>

  <body>
    <%= render "shared/navbar" unless current_page?(new_rsvp_path) || current_page?(rsvps_path) || current_page?(albums_path) || current_page?(edit_album_path(@photo_album)) || current_page?(album_path(@photo_album) || current_page?(root)) %>
    <%= render "shared/flashes" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<a id="home">
  <img src="https://res.cloudinary.com/dfipoufmj/image/upload/v1666015811/DSC02450_dmkao8.jpg" alt="" class="five" >
</a>
<div class="welcome-info">
  <h1>The Jackson-Addletons</h1>
  <p>Welcome! We may already be legally wed, but that doesn't mean we're missing the opportunity to celebrate with our nearest and dearest!</p>
  <div class="music">
    <i class="fa-brands fa-spotify" style="font-size: 70px; color: #1cd05d"></i>
    <audio controls src="https://res.cloudinary.com/dfipoufmj/video/upload/v1675534541/This_Will_Be_An_Everlasting_Love_mutyct.mp3"></audio>
  </div>
  <p>Suit up, boot up, and get ready for a Scottish throwdown!</p>
  <p id="demo"></p>

  <a id="rsvp">
  </a>
  <a href="https://www.thebyreatinchyra.co.uk/" target="_blank"><h2>25th November 2023 | The Byre at Inchyra</h2><h3>Glencarse, Perth PH2 7LU, UK</h3>
  </a>
</div>
  <script>
    var countDownDate = new Date("Nov 23, 2023 12:00:00").getTime();
    var x = setInterval(function() {
      var now = new Date().getTime();
    var distance = countDownDate - now;
    var days = Math.floor(distance / (1000 * 60 * 60 * 24));
    var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
    var seconds = Math.floor((distance % (1000 * 60)) / 1000);
      document.getElementById("demo").innerHTML = days + " Days - " + hours + " Hours - "
      + minutes + " Minutes and " + seconds + " Seconds" + " TO GO!";

      if (distance < 0) {
        clearInterval(x);
        document.getElementById("demo").innerHTML = "Its the Big Day!";
      }
    }, 1000);
  </script>
<div class="rsvp-area">
  <div class="area-image">
    <img src="https://res.cloudinary.com/dfipoufmj/image/upload/v1666015815/DSC02516_hw35a6.jpg" alt="" class="six">
  </div>
  <div class="rsvp-area-2">
    <div class="rsvp-area-info">
      <h4>PLEASE RSVP BY 30th APRIL 2023</h4>
        <p>Fill out the form below</p>
      <div class="rsvp-btn">
        <a href="/rsvps/new"><p id="rsvp-big-button">RSVP</p></a>
      </div>
      <a id="details">
      </a>
        <div class="rsvp-table-btn">
          <%= link_to "RSVP replies", rsvps_path, id: "rsvp-table-button" %>
        </div>
    </div>
  </div>
</div>

<div class="details-area">
  <div class="details-area-info">
    <h1>The Details</h1>
    <h4>Dress Code</h4>
    <p>Formal & Fancy (be prepared for potentially frosty weather)</p>
    <p><strong>* umbrellas strongly advised *</strong></p>
    <p>Venue details & access - <a href="https://www.thebyreatinchyra.co.uk/getting-here/information-for-guests/" target="_blank" id="parking-link">Click Here</a></p>
    <p>ADULT ONLY AFFAIR</p>
    <p>Mealtimes & toasts are on us, party drinks are on you.*</p>
    <p>Any Questions? zoeandcam2023@gmail.com</p>
    <p id="side-note">* If you prefer something a little stronger than vino, we will have a semi-subsidised bar that accepts all major debit / credit cards. No naughty hipflasks or outside beverages please - it interferes with licensing and will shut down our throwdown!</p>
  </div>
  <div class="area-image">
    <img src="https://res.cloudinary.com/dfipoufmj/image/upload/v1666015814/DSC02500_wn01f3.jpg" alt="" class="two">
  </div>
</div>
<a id="wedding-committee">
</a>
<div class="wedding-committee-area">
  <h1 class="wedding-committee-titles">Bridesmaids</h1>
  <div class="bridesmaids">
    <div class="bridesmaids-list">
      <div class="vip">
        <img src="https://res.cloudinary.com/dfipoufmj/image/upload/v1666112213/zoe4_eqjnhe.jpg" alt="" class="avatar">
        <div class="card-info">
          <h4>Louisa Abbott</h4>
          <h5>The Ginger One</h5>
        </div>
      </div>
      <div class="vip">
        <img src="https://res.cloudinary.com/dfipoufmj/image/upload/v1666112213/zoe6_zaw9zf.jpg" alt="" class="avatar">
        <div class="card-info">
          <h4>Ruby Gullon</h4>
          <h5>The Geordie</h5>
        </div>
      </div>
      <div class="vip">
        <img src="https://res.cloudinary.com/dfipoufmj/image/upload/v1666166533/alicia_z6bkdd.jpg" alt="" class="avatar">
        <div class="card-info">
            <h4>Alicia Hudson</h4>
          <h5>Twinny</h5>
        </div>
      </div>
      <div class="vip">
        <img src="https://res.cloudinary.com/dfipoufmj/image/upload/v1669751716/orla_zoeandcam_m8eghc.jpg" alt="" class="avatar">
        <div class="card-info">
          <h4>Orla Jackson</h4>
          <h5>Little Sis</h5>
        </div>
      </div>
      <div class="vip">
        <img src="https://res.cloudinary.com/dfipoufmj/image/upload/v1666112213/zoe5_d0hcqx.jpg" alt="" class="avatar">
        <div class="card-info">
          <h4>Mairead Kempthorne</h4>
          <h5>Lord Maz</h5>
        </div>
      </div>
      <div class="vip">
        <img src="https://res.cloudinary.com/dfipoufmj/image/upload/v1666112212/zoe1_mgsxq7.jpg" alt="" class="avatar">
        <div class="card-info">
          <h4>Rosie Littlejohns</h4>
          <h5>Rozatron</h5>
        </div>
      </div>
      <div class="vip">
        <img src="https://res.cloudinary.com/dfipoufmj/image/upload/v1668433845/WhatsApp_Image_2022-10-20_at_5.00.58_AM_zeecty.jpg" alt="" class="avatar">
        <div class="card-info">
          <h4>Hannah Snodgrass</h4>
          <h5>The American</h5>
        </div>
      </div>
      <div class="vip">
        <img src="https://res.cloudinary.com/dfipoufmj/image/upload/v1666166524/sonnen_ho7gzn.jpg" alt="" class="avatar">
        <div class="card-info">
          <h4>Lesley Sonnen</h4>
          <h5>The Foghorn</h5>
        </div>
      </div>
      <div class="vip">
        <img src="https://res.cloudinary.com/dfipoufmj/image/upload/v1666166640/zoe3_ps4f4y.jpg" alt="" class="avatar">
        <div class="card-info">
          <h4>Bethan Ward</h4>
          <h5>The Mancunian</h5>
        </div>
      </div>
    </div>
  </div>
  <h1 class="wedding-committee-titles">Groomsmen</h1>
  <div class="groomsmen">
    <div class="groomsmen-list">
      <div class="vip">
        <img src="https://res.cloudinary.com/dfipoufmj/image/upload/v1668424862/allen-zoeandcam_pqtgyg.jpg" alt="" class="avatar">
        <div class="card-info">
          <h4>Allen Butler</h4>
          <h5>The Best Man</h5>
        </div>
      </div>
      <div class="vip">
        <img src="https://res.cloudinary.com/dfipoufmj/image/upload/v1666713252/iain_zoe_and_cam_z0wutt.jpg" alt="" class="avatar">
        <div class="card-info">
          <h4>Iain Addleton</h4>
          <h5>The Brother</h5>
        </div>
      </div>
      <div class="vip">
        <img src="https://res.cloudinary.com/dfipoufmj/image/upload/v1668424478/WhatsApp_Image_2022-11-12_at_7.51.16_PM_psu7rj.jpg" alt="" class="avatar">
        <div class="card-info">
          <h4>Henry Faber</h4>
          <h5>The Semi-Hot One</h5>
        </div>
      </div>
      <div class="vip">
        <img src="https://res.cloudinary.com/dfipoufmj/image/upload/v1666705917/Jay_Favaro_zoeandcam_t02qsn.jpg" alt="" class="avatar">
        <div class="card-info">
          <h4>Jay Favaro</h4>
          <h5>The Semi-Athletic One</h5>
        </div>
      </div>
      <div class="vip">
        <img src="https://res.cloudinary.com/dfipoufmj/image/upload/v1668424478/WhatsApp_Image_2022-11-12_at_7.51.35_PM_mqsefr.jpg" alt="" class="avatar">
        <div class="card-info">
          <h4>Matthew Farkas</h4>
          <h5>The Semi-Large One</h5>
        </div>
      </div>
      <div class="vip">
        <img src="https://res.cloudinary.com/dfipoufmj/image/upload/v1666713856/rory_zoeandcam_a29pkj_qdktj3.jpg" alt="" class="avatar">
        <div class="card-info">
          <h4>Rory Jackson</h4>
          <h5>The Bro In Law</h5>
        </div>
      </div>
      <div class="vip">
        <img src="https://res.cloudinary.com/dfipoufmj/image/upload/v1668425007/WhatsApp_Image_2022-11-12_at_7.51.25_PM_s95hwo.jpg" alt="" class="avatar">
        <div class="card-info">
          <h4>Michael Hennessy</h4>
          <h5>The Hairy One</h5>
        </div>
      </div>
      <div class="vip">
        <img src="https://res.cloudinary.com/dfipoufmj/image/upload/v1668424478/WhatsApp_Image_2022-11-12_at_7.50.48_PM_akqwdg.jpg" alt="" class="avatar">
        <div class="card-info">
          <h4>Daniel Sutherland</h4>
          <h5>Suds</h5>
        </div>
      </div>
      <div class="vip">
        <img src="https://res.cloudinary.com/dfipoufmj/image/upload/v1668424478/WhatsApp_Image_2022-11-12_at_7.51.05_PM_naqhvz.jpg" alt="" class="avatar">
        <div class="card-info">
          <h4>Nick Thrasher</h4>
          <h5>The Very Tall One</h5>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="image-break">
  <img src="https://res.cloudinary.com/dfipoufmj/image/upload/v1669048233/zoe_header_pic_q6rlbj.jpg" alt="" class="four">
  <img src="https://res.cloudinary.com/dfipoufmj/image/upload/v1669048522/zoe_header_pic_2_nsu9ml.jpg" alt="" class="nine">
</div>
<a id="schedule">
</a>
<div class="schedule-area">
  <div class="travel">
    <div class="travel-info">
      <h2>Travel & Accommodation</h2>
      <br/>
      <p>We have reserved a number of rooms at Travelodge Broxden (10 mins from our venue). If you are interested in cheap and cheerful and would like to reserve a room please <a href="#bottom"><strong>click here</strong></a>. We have secured a heavily discounted rate that you will only get by booking through us. (£119 per room / night)</p>
      <p>There are also ample accommodation options nearby ranging from Premier and Holiday Inns to 5* resorts and self-catering cottages.</p>
      <p>The venue has a list of local suggestions, but you should also be able to find plenty of options via booking.com or a good old fashioned Google search.</p>
      <a href="https://www.thebyreatinchyra.co.uk/place-weddings-perthshire/places-to-stay/" target="_blank"><p id="click-here-travel"><strong>Click here</strong></p></a>
      <p>If you're feeling brave, the estate offers free on-site camping with use of the bathroom facilities. Please do let us know if you're interested!</p>
    </div>
  </div>
  <div class="schedule">
      <h1>Order of the day</h1>
    <div class="schedule-list">
      <div class="schedule-event">
        <h5>1:30pm | Arrival of guests 👋🏼</h5>
      </div>
      <p>~</p>
      <div class="schedule-event">
        <h5>2:00pm | Ceremony 🕊</h5>
      </div>
      <p>~</p>
      <div class="schedule-event">
        <h5>2:30pm | Canapés 🫒</h5>
      </div>
      <p>~</p>
      <div class="schedule-event">
        <h5>4:00pm | Wedding breakfast 🐷</h5>
      </div>
      <p>~</p>
      <div class="schedule-event">
        <h5>7:00pm | Evening guests arrival 🥳</h5>
      </div>
      <p>~</p>
      <div class="schedule-event">
        <h5>12:00am | Carriages 💤</h5>
      </div>
    </div>
  </div>
  <div class="registry">
    <div class="regsitry-info">
      <h2>Registry</h2>
      <p>COMING SOON</p>
    </div>
  </div>
</div>
<div class="travelodge">
  <p style="font-size: 22px;">If you would like to book Travelodge, Broxden Junction Perth, please email <strong style="text-decoration: underline;">zoeandcam2023@gmail.com</strong> and include the following information:</p>
  <br/>
  <h2>Names for Booking</h2>
  <br/>
  <p>First Name & Surname</p>
  <br/>
  <h2>Which nights would you like to book</h2>
    <br/>
    <p>Fri 24th & Sat 25th November 2023 (£119 per night for a double or twin room)</p>
    <p>24th only | 25th only | Additional night (please specify)</p>
    <br/>
  <h2>Room Type</h2>
    <br/>
    <p>Double Room / Twin Room </p>
    <p>Family Room: 1 Double bed & 1 Single for Additional Adult (extra charge of £10 for 24th and £15 for 25th)</p>
    <br/>
  <h4 style="text-align: center; font-weight: normal;">* 10% deposit will be required within 2 weeks of booking, full payment will be required by 1st October 2023. *</h4>
  <h4 style="text-align: center; font-weight: bold; font-style: normal">Thank you!</h4>
</div>
<div class="footer" id="bottom">
    <p>Built by B.O.B</p>
    <img src="https://res.cloudinary.com/dfipoufmj/image/upload/v1669115799/image-from-rawpixel-id-2615398-png_ba0qxs.png" alt="" class="ten">
</div>

app/views/pages/thankyou.html.erb
<h1>Thank you for Letting us know!!!</h1>
<p>We cant wait to partaaaay with you!! If You cant make it, not to worry I'm sure we will catch up with you soon 🥳</p>
  <a href="/"><h3>Return Home</h3></a>

app/views/rsvps/index.html.erb
<h2>Total guests coming</h2>
<p><%= @total_participants %></p>
<h2><%= link_to "Return home", root_path %></h2>


<div class="table-container">
  <table class="table">
    <tr class="rsvp-table-headers">
      <th>NAME</th>
      <th>COMING?</th>
      <th>DIET</th>
      <th>SONG</th>
    </tr>
    <% @rsvps.each do |rsvp| %>
    <tr class="rsvp-data">
      <td><%=rsvp.name%></td>
      <td><%=rsvp.attendance%></td>
      <td><%=rsvp.diet%></td>
      <td><%=rsvp.song%></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/rsvps/new.html.erb
<div class="rsvp-card-product">
  <img src="https://res.cloudinary.com/dfipoufmj/image/upload/v1668425666/WhatsApp_Image_2022-11-09_at_11.37.09_PM_w2epfo.jpg" alt="" class="rsvp-new-img">
  <div class="rsvp-form-body">
    <a href="/"><h3>Return Home</h3></a>
    <h2 class="reply-text" id="rsvp-title" style="margin: 20px;">Please fill the form out <strong>ONCE</strong> per attendee</h2>
    <div class="rsvp-form">
      <%= simple_form_for(@rsvp) do |f| %>
        <%= f.input :name, :label => "Please write your FULL name", required: true %>
        <%= f.input :attendance, as: :radio_buttons, collection: [['Yes', "Yes!! I'm coming!"], ['No', "No, sadly I can't come 😢"]], label_method: :second, value_method: :first, required: true %>
        <%= f.input :song, :label => "Name a song that we can add to our wedding playlist!" %>
        <%= f.input :diet, :label => "Any dietary requirements?" %>
        <div id="rsvp-confirm">
          <%= f.submit "Complete the form", class: "rsvp_button btn-flat" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<ul class="navbar">
  <li class="log-item">
    <%= link_to "Home", "#home", class: "nav-link" %>
  </li>
  <li class="log-item">
    <%= link_to "Details", "#details", class: "nav-link" %>
  </li>
  <li class="log-item">
    <%= link_to "RSVP", new_rsvp_path, class: "nav-link" %>
  </li>
  <li class="log-item">
    <%= link_to "Wedding Committee", "#wedding-committee", class: "nav-link" %>
  </li>
  <li class="log-item">
    <%= link_to "Information", "#schedule", class: "nav-link" %>
  </li>
  <li class="log-item">
    <%= link_to "Photo Album", album_path(@photo_album), class: "nav-link" %>
  </li>
</ul>